---
title: "Xin's Resume"
---

Xin Zheng  
100 Haven Avenue, Tower 3, New York, NY, 10032  
E-mail: xz2677@cumc.columbia.edu  

**EDUCATION**  
**Beijing Forestry University, China**　　　　　　　　　　　　　09/2013-06/2017  
Biological Science, BS

**Columbia University, United States**　　　　　　　　　　　    09/2017-06/2019  
Biostatistics, MS

  
**RESEARCH EXPERIENCE**  
**Research on Black Film covering for eliminating Oncomelania, China**　　　         07/2016-08/2016 

*Instruaction:In this project, we plan to place thicken black plastic film mulch over vegetation soil, to keep the temperature steady, and investigate the time needed to interrupt the photosynthesis and kill plants in spring and winter. By eliminating the food of the Oncomelania in order to control the snails' reproduction, we can control the reproduction and spread ofschistosomiasis.*

**A Study on Cedarwood Leaves’ Polarization and its Regulatory Molecule Mechanism,China**　　　07/2016-08/2016

*Instruction: I led a team, wrote the research proposal and won 1,400USD municipal scholarship support from the National College Students' Innovation Competition. I organized team members to design the experiment. We collected and compared structures of green cedar and grey branch cedar leaves. We also detected chlorophyll fluorescence parameters and used R to sort and analyze data. In the end, we obtained the leaf structures, observed the lignin’s autofluorescence through the fluorescent microscope, made charts and graphs and found there was no major difference.*

**Work experience**  
**CDC of Sichuan Province, Intern**  
*Participated in research projects*  
*Took part in policy meetings hosted by local branches of CDC*  
*Made investigation about local public health situation*  
*Collected data about different public health issues and programs*  
*Helped researchers to do evaluation and compose research reports*  

**Zhuiyuanyun Education Company, Team leader of Customer Service**  
*Helped students learn TOFEL, CET6*  
*In charge of the communication between teachers and students*  
*Arranged manager’s schedule as well as teachers’ teaching schedules*  
*Organized weekly meetings.*
  
**ACTIVITIES& HONORS**  
*Vice President, Student Union, Beijing Forestry University*  
*Minister, PR department, Student Union, Beijing Forestry University Member, PR department, Student Union*  *Beijing Forestry University Etiquette Member, Beijing Forestry University*  
*Excellent Students Leader, Beijing Forestry University*  
*Third Prize Scholarship for academic excellence*

